Modul6/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/AddNewPost', 'AddNewPostController@index')->name('AddNewPost');
Route::get('/Profile', 'ProfileEditController@index')->name('Profile');
Route::get('/EditProfile', 'ProfileEditController@edit')->name('EditProfile');
Route::post('/Profile/update', 'ProfileEditController@updateProfile')->name('EditProfile');
Route::get('likeposts/{id}','HomeController@like')->name('Like');
Route::get('/Detailpost/{Detailpost}', 'HomeController@specific')->name('Detailpost');
Route::get('/comment', 'HomeController@addkomen')->name('comment');
Route::post('/Home', 'HomeController@store')->name('Home');
Route::resource('AddNewPost','AddNewPostController');

Modul6/app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    //
    protected $table ="komentar_posts";
    protected $fillable = [
        'id','user_id','post_id', 'comment','create_at','update_at',
    ];
public function post(){   
    return $this->belongsTo('App\Posts','post_id');
}
public function user(){
    return $this ->belongsTo('App\User','user_id');
}
}

Modul6/app/Posts.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Posts extends Model
{
    //
     protected $table='posts';
     protected $fillable = ['user_id','caption', 'image'
    ];   

    public function comment(){
        return $this->hasMany('App\Comment','post_id','id');
    }
    public function users(){
        return $this->belongsto('App\User','user_id');
    }
}

Modul6/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

Modul6/app/Http/Controllers/AddNewPostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Posts;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
class AddNewPostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('AddNewPost');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $imagename = 'img/'.time().'.'.$request->file('foto')->getClientOriginalExtension();
        $request['foto']->move(base_path().'/public/img',$imagename);
        $post=new posts;
        $post->user_id=$request->id;
        $post->caption=$request->caption;
        $post->image=$imagename;
        $post->save();
        return redirect('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

Modul6/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

Modul6/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Posts;
use App\User;
use App\Comment;
class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $posts= Posts::get();        
        return view('home',[ 'post'=>$posts]);
       
    }
    public function like($id){
        posts::find($id)->increment('likes');
        return redirect('home');
    }
    public function specific($id){
    
     
        $posts = posts::find($id);
        return view('Detailpost',['posts'=>$posts]);
      
    }

    
    public function store(){
    dd(request()->all());  
    }
 public function addkomen(Request $request){
     $comment = new Comment();
     $comment->user_id =$request->user_id;
     $comment->post_id =$request->post_id;
     $comment->comment =$request->komen;
     $comment->save();
     return redirect('home');
}
public function editprofil(){
    return view('EditProfile');
}

}

Modul6/app/Http/Controllers/ProfileEditController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use App\User;
class ProfileEditController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('Profile');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
        //
        return view('EditProfile');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    
public function updateProfile(Request $request)
{     
    $imagename = 'img/'.time().'.'.$request->file('image')->getClientOriginalExtension();
    $request['image']->move(base_path().'/public/img',$imagename);
    $user = User::find($request->id);
    $user->title = $request->input('title');
    $user->description = $request->input('description');
    $user->url = $request->input('url');
    $user->avatar = $imagename;   
    $user->save();

    return redirect('/Profile');
}
    
}

Modul6/resources/views/AddNewPost.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
            <div class="col-8 offset-2">
 
                <div class="row">
                    <h1>Add New Post</h1>
                </div>
                <label for="caption" class="col-md-4 col-form-label">Post Caption</label>
<form action="{{route('AddNewPost.store')}}" method="put" enctype="multipart/form-data">
    {{csrf_field()}}
    
    <input type="hidden" value="{{Auth::id()}}" name="id"><br>
    <input type="text" name="caption"> <br><br>
    <input type="file" name="foto"> <br><br>
    <input type="submit" value="new post">
    
</form>

@endsection

Modul6/resources/views/Detailpost.blade.php
@extends('layouts.app')
@section('content')
<div class="card mb-3 w-10" style="max-width: 100%px;">
  <div class="row no-gutters">
    <div class="col-md-6">
      <img src="../{{$posts->image}}" class="card-img" alt="post_image">
    </div>

    <div class="col-md-6">
 
      <div class="card-body">
     
      <img src="../../{{$posts->users['avatar']}}" style="width:2rem" class="rounded-circle" >  <h5 class="card-title" ><b>{{ $posts->users['name'] }}</b></h5x><hr>
        <p class="card-title" ><b>{{ $posts->users['email'] }}</b>{{ $posts->caption}}</p>
        
        
        @foreach($posts->comment as $komen)
        <b>{{ $komen->user['email']}}</b>
       {{$komen['comment']}}
       
       <br>
       @endforeach
       <hr>
       <a href="{{ route('Like',['id'=>$posts->id]) }}"><button class="btn" name="direct" value="home" type="submit"><i class="fa fa-heart-o"></i></button>
        <a href="{{ route('Detailpost',$posts->id)}}"><i class="fa fa-comment-o"></i></a>
        <p><b>{{$posts->likes}}</b>likes</p>
    <input type="text" class="form-control" placeholder="Add a Comment..."
                                            name="komen">
                                           
      </div>
    </div>
  </div>
</div>
@endsection

Modul6/resources/views/EditProfile.blade.php
@extends('layouts.app')
@section('content')

<form action="/Profile/update" method="post" enctype="multipart/form-data">
    @csrf
    <input type="hidden" name="Id" value="{{Auth::user()->id}}">
    <div class="row">
        <div class="col-8 offset-2">

            <div class="row">
                <h1>Edit Profile</h1>
            </div>
            <div class="form-group row">
                <label for="title" class="col-md-4 col-form-label">Title</label>

                <input id="title" type="text" class="form-control" name="title" value="" autocomplete="title" autofocus>

            </div>

            <div class="form-group row">
                <label for="description" class="col-md-4 col-form-label">Description</label>

                <input id="description" type="text" class="form-control" name="description" value=""
                    autocomplete="description" autofocus>

            </div>

            <div class="form-group row">
                <label for="url" class="col-md-4 col-form-label">URL</label>

                <input id="url" type="text" class="form-control" name="url" value="" autocomplete="url" autofocus>

            </div>

            <div class="row">
                <label for="image" class="col-md-4 col-form-label">Profile Image</label>

                <input type="file" class="form-control-file" id="image" name="image">

            </div>

            <div class="row pt-4">
                <button class="btn btn-primary">Save Profile</button>
            </div>

        </div>
    </div>
</form>
@endsection

Modul6/resources/views/Home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-5">
            @foreach($post as $pos)
            <div class="card">
                <div class="card-header">
                    <div class="container ">
                        <div class="row">
                            <div class="col-2">
                                <img src="{{$pos->users['avatar']}}" class="rounded-circle" alt="kosonggg" width="100%"
                                    height="35">
                            </div>
                           
                                <span class="text-dark"><b>{{$pos->users['name']}}</b></span> </a>
                        </div>
                    </div>

                </div>
                <a href="{{route('Detailpost',$pos->id)}}">
                    <img src="{{ $pos->image }}" style="width:100%; height:350px;" alt="kosong"></a>
                <div class="card-header">
                    <div class="container">
                        <p>
                        
                            <a href="{{ route('Like',['id'=>$pos->id]) }}"><i class="fa fa-heart-o"></i>

                            <a href="{{route('Detailpost',$pos->id)}}"><i class="fa fa-comment-o"></i></a>
                                <p><b>{{$pos->likes}}</b>likes</p>
                           
                                    <span class="text-dark"> <b>{{$pos->users['email']}}</b></a>
                                <p>{{ $pos->caption }}</p>
                                   <form action="{{route('comment')}}" method="get">

                                <form method="" enctype="multipart/form-data">
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" placeholder="Recipient's Name"
                                            name="komen">
                                            <input type="hidden" class="form-control" value="{{$pos->id}}"
                                            name="post_id">
                                            <input type="hidden" class="form-control" value="{{ Auth::user()->id}}"
                                            name="user_id">
                                        <div class="input-group-append">
                                            <button class="btn btn-success" type="submit"
                                                style="background-color:grey;">Post</button>
                                        </div>
</form>
                                    </div>

                    </div>
                </div>
            </div>
            <br>
            @endforeach
        </div>
    </div>
    @endsection

Modul6/resources/views/Profile.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
    <div class="row">
        <div class="col-3 p-5">
            <img src="{{Auth::user()->avatar}}" alt="gambar" class="rounded-circle w-100">
        </div>
        <div class="col-9 pt-5">
    
            <div class="d-flex justify-content-between align-items-baseline">
                <div class="d-flex align-items-center pb-3">
                    <div class="h4">{{Auth::user()->name}} </div>
                </div>
                  <a href="{{route('AddNewPost.index')}}">Add New Post</a>  
            </div>
         
            
          
                <a href="/EditProfile">Edit Profile</a>
            
            <div class="d-flex">
                <div class="pr-5"><strong> ...</strong> posts</div><br>
               <p>{{Auth::user()->title}}</p><br><br>
               <p>{{Auth::user()->description}}</p>
               <p>{{Auth::user()->url}}</p>
            </div>
            <div class="pt-4 font-weight-bold"></div>
            <div></div>
            
            <div><a href=""></a></div>
        </div>
    </div>

    <div class="row pt-5">
            </div>
</div>

@endsection

Modul6/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/home') }}">
                <img src="../{{ ('img/ead.PNG') }}" style="width:60px; height:40px; border-right:1px solid #000000" class="pr-3">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
            <li><b><h5>Enterprise Application Development</h5></b></li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="/Profile">Profile</a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>